spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
#    spring.cloud.config.enabled=false or
#    spring.cloud.config.import-check.enabled=false.
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
zuul:
  #关闭默认路由配置
  ignored-services: '*'
  prefix: /api  #请求前缀  /api/goods/xxx
  routes:
    #给服务配置路由
    microservice-goods:
      path: /goods/**
      serviceId: MICROSERVICE-GOODS
    microservice-user:
      path: /user/**
      serviceId: MICROSERVICE-USER
      # 设置cookie可以传到服务器
      sensitiveHeaders: true
  host:
    socket-timeout-millis: 30000
    #服务的http客户端连接池最大连接, 默认200
    max-total-connections: 500
    #每个route可用的最大连接数, 默认20
    max-per-route-connections: 50
    #Zuul在请求路由时，默认会过滤掉一些敏感的头信息，以下配置可以防止路由时的Cookie及Authorization的丢失：
    #配置过滤敏感的请求头信息，设置为空就不会过滤
    sensitive-headers: Cookie,Set-Cookie,Authorization
    #Zuul在请求路由时，不会设置最初的host头信息。设置为true重定向是会添加host请求头
    add-host-header: true

